[package]
name = "use-grid-search"
description = "Primitive one-dimensional and two-dimensional grid search helpers"
publish = true
authors.workspace = true
version.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
readme = "README.md"
documentation = "https://docs.rs/use-grid-search"
keywords = ["grid", "search", "optimization", "objective", "score"]
categories = ["algorithms", "mathematics", "science"]

[dependencies]
use-objective.workspace = true

[lints]
workspace = true
